# Generated by Django 4.2.8 on 2023-12-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutMe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("internship", "Internship"),
                    ("extracurricular", "Extracurricular Activities"),
                    ("research", "Research"),
                ],
                default="all",  # Set the default category
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="title",
            field=models.CharField(max_length=100),
        ),
    ]
