# Generated by Django 4.2.8 on 2023-12-30 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_aboutme_portfolioitem_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioitem",
            name="subtitle",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
