# Generated by Django 4.2.8 on 2023-12-30 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_language_resume_technicalskill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="language", name="name", field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="language",
            name="proficiency",
            field=models.CharField(
                choices=[
                    ("Novice", "Novice"),
                    ("Advanced Beginner", "Advanced Beginner"),
                    ("Competent", "Competent"),
                    ("Proficient", "Proficient"),
                    ("Expert", "Expert"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="technicalskill",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="technicalskill",
            name="proficiency",
            field=models.CharField(
                choices=[
                    ("Novice", "Novice"),
                    ("Advanced Beginner", "Advanced Beginner"),
                    ("Competent", "Competent"),
                    ("Proficient", "Proficient"),
                    ("Expert", "Expert"),
                ],
                max_length=50,
            ),
        ),
    ]
