# Generated by Django 4.2.8 on 2024-01-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0006_personalinfo"),
    ]

    operations = [
        migrations.AddField(
            model_name="personalinfo",
            name="github_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="personalinfo",
            name="linkedin_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
