# Generated by Django 4.2.8 on 2024-01-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0007_personalinfo_github_link_personalinfo_linkedin_link"),
    ]

    operations = [
        migrations.RemoveField(model_name="personalinfo", name="github_link",),
        migrations.RemoveField(model_name="personalinfo", name="linkedin_link",),
        migrations.AddField(
            model_name="portfolioitem",
            name="duration",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
