# Generated by Django 4.2.8 on 2024-01-02 22:59

from django.db import migrations, models
import django.utils.timezone
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0008_remove_personalinfo_github_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioitem",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="description",
            field=portfolio.models.TruncatingTextField(),
        ),
    ]
