# Generated by Django 4.2.8 on 2024-01-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0010_category_remove_portfolioitem_category_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="portfolioitem", name="categories",),
        migrations.AddField(
            model_name="portfolioitem",
            name="category",
            field=models.CharField(
                choices=[
                    ("all", "All"),
                    ("internship", "Internship"),
                    ("extracurricular", "Extracurricular Activities"),
                    ("research", "Research"),
                ],
                default="all",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="portfolioitem",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
