# Generated by Django 4.2.8 on 2024-01-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0011_remove_portfolioitem_categories_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="portfolioitem", name="category",),
        migrations.RemoveField(model_name="portfolioitem", name="created_at",),
        migrations.RemoveField(model_name="portfolioitem", name="updated_at",),
        migrations.AddField(
            model_name="portfolioitem",
            name="categories",
            field=models.ManyToManyField(to="portfolio.category"),
        ),
        migrations.AlterField(
            model_name="category", name="name", field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="portfolioitem", name="description", field=models.TextField(),
        ),
    ]
