# Generated by Django 4.2.8 on 2024-01-04 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0012_remove_portfolioitem_category_and_more"),
    ]

    operations = []
