name: Deploy Code to Release Branch 🚀
on:
  workflow_dispatch:

jobs:
  build:
    name: Push to Release Branch
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy 🚀
        uses: estherpark514/github-pages-deploy-action@v4
        with:
          branch: releases/v4
          folder: dist
          clean: false
          single-commit: true
